export const itemTypeMap = new Map([
  // ["爪", "Claws"],
  // ["匕首", "Daggers"],
  // ["单手剑", "One_Hand_Swords"],
  // ["单手斧", "One_Hand_Axes"],
  // ["连枷", "Flails"],
  // ["双手剑", "Two_Hand_Swords"],
  // ["双手斧", "Two_Hand_Axes"],
  // ["鱼竿", "Fishing_Rods"],
  // ["陷阱", "Traps"],
  ["法杖", "Wands"],
  ["法器", "Foci"],
  ["长杖", "Staves"],
  ["短杖", "Sceptres"],
  ["节杖", "Quarterstaves"],
  ["战矛", "Spears"],
  ["战弩", "Crossbows"],
  ["弓", "Bows"],
  ["箭袋", "Quivers"],

  ["项链", "Amulets"],
  ["戒指", "Rings"],
  ["腰带", "Belts"],
  ["咒符", "Charms"],
  ["生命药剂", "Life_Flasks"],
  ["魔力药剂", "Mana_Flasks"],

  ["单手锤", "One_Hand_Maces"],
  ["双手锤", "Two_Hand_Maces"],
  ["盾牌", "Shields"],
  ["轻盾", "Bucklers"],

  ["手套(护甲)", "Gloves_str"],
  ["鞋子(护甲)", "Boots_str"],
  ["胸甲(护甲)", "Body_Armours_str"],
  ["头部(护甲)", "Helmets_str"],

  ["手套(闪避)", "Gloves_dex"],
  ["鞋子(闪避)", "Boots_dex"],
  ["胸甲(闪避)", "Body_Armours_dex"],
  ["头部(闪避)", "Helmets_dex"],

  ["手套(护盾)", "Gloves_int"],
  ["鞋子(护盾)", "Boots_int"],
  ["胸甲(护盾)", "Body_Armours_int"],
  ["头部(护盾)", "Helmets_int"],

  // ["咒符", "Charms"],
  // ["可堆叠通货", "Stackable_Currency"],
  // ["可镶嵌", "Socketable"],
  // ["预兆", "Omen"],
  // ["液化情感", "Liquid_Emotions"],
  // ["精华", "Essence"],
  // ["裂片", "Splinter"],
  // ["催化剂", "Catalysts"],
  // ["引路石", "Waystones"],
  // ["地图碎片", "Map_Fragments"],
  // ["先祖秘藏日志", "Expedition_Logbooks"],
  // ["贪婪战书", "Inscribed_Ultimatum"],
  // ["石板", "Tablet"],
  // ["试炼硬币", "Trial_Coins"],
  // ["巅峰钥匙", "Pinnacle_Keys"],
  // ["珠宝", "Jewels"],
  // ["宝库钥匙", "Vault_Keys"],
  // ["遗物", "Relics"],
  // ["藏身处", "Hideout"],
  // ["保险箱", "Strongbox"]
]);
